/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Editing.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Editing(props) {
  const { nodes, materials } = useGLTF('/models/Editing.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cylinder003_3.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cylinder003_4.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.Cylinder003_5.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.Cylinder003_6.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cylinder003_7.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cylinder003_8.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.Cylinder003_9.geometry} material={materials['Material.010']} />
    </group>
  )
}

useGLTF.preload('/models/Editing.glb')
