"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/icon.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Icon({
  position,
  rotation = [0, -0.5, 0],
  scale = 0.4,
  ...props
}) {
  const { nodes, materials } = useGLTF("/models/icon.glb");
  const ModelRef = useRef(null);

  useFrame((state, delta) => {
    if (ModelRef.current) {
      ModelRef.current.rotation.z -= .2 * delta; // 0.5 radians per second rotation speed
    }
  });

  return (
    <group
      ref={ModelRef}
      position={position}
      rotation={rotation}
      scale={scale}
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.Circle005.geometry}
        material={materials["Material.001"]}
        position={[0, 0, -0.009]}
      />
    </group>
  );
}

useGLTF.preload("/models/icon.glb");
